image: maven:eclipse-temurin

stages:
  - build
  - test
  - package


build:
  stage: build-backend
  script:
    - cd SpareSti
    - mvn compile

test:
  stage: test-backend
  script:
    - cd SpareSti
    - mvn verify
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

package:
  stage: package-backend
  script:
    - cd SpareSti
    - mvn clean package
